set(_CATKIN_CURRENT_PACKAGE "frame_registration")
set(frame_registration_MAINTAINER "carlos <carlos@todo.todo>")
set(frame_registration_DEPRECATED "")
set(frame_registration_VERSION "0.0.0")
set(frame_registration_BUILD_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "pcl_ros" "cv_bridge" "libg2o" "opencv2" "libpcl-all-dev" "rospy" "ekz_public_lib")
set(frame_registration_RUN_DEPENDS "geometry_msgs" "roscpp" "sensor_msgs" "std_msgs" "pcl_ros" "cv_bridge" "libg2o" "opencv2" "libpcl-all" "rospy" "ekz_public_lib")
set(frame_registration_BUILDTOOL_DEPENDS "catkin")